spring.application.name=CampusConnect


//database
spring.datasource.url=jdbc:mysql://localhost:3306/campus_connect
spring.datasource.username=root
spring.datasource.password=root@39
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

//hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

//cloud connection
cloudinary.cloud_name=campus_connect
cloudinary.api_key=759212235121247
cloudinary.api_secret=M51iR4tsxWpssdcM7AzhmLwrkGM

